services:
  flask_app:
    container_name: flask_app
    restart: "no"
    build: ./web
    ports:
      - "8000:8000"
    command: gunicorn -w  1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: "no"
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app